format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[ðŸžˆ](#a6e3a1 bold)"
error_symbol = "[ðŸžˆ](#f38ba8)"
vicmd_symbol = "[ðŸžˆ](#f9e2af)"

[directory]
format = "[î‚¶]($style)[(bg:#f5c2e7 fg:#eba0ac)$path](bg:#f5c2e7 fg:#a84c8d)[î‚´ ]($style)"
style = "bg:#1a1b26 fg:#f5c2e7"

[git_branch]
format = "[î‚¶]($style)[[ï‡“ ](bg:#f5c2e7 fg:#a84c8d bold)$branch](bg:#f5c2e7 fg:#4c4f69)[î‚´ ]($style)"
style = "bg:#1a1b26 fg:#f5c2e7"
